---
- name: Start GPUStack worker nodes
  hosts: worker
  tasks:
    - name: Start GPUstack
      become: true
      ansible.builtin.systemd_service:
        name: gpustack
        state: started
        enabled: true

- name: Start GPUStack controller node
  hosts: controller
  tasks:
    - name: Start GPUstack
      become: true
      ansible.builtin.systemd_service:
        name: gpustack
        state: started
        enabled: true
