---
- name: Stop GPUStack worker nodes
  hosts: worker
  tasks:
    - name: Stop GPUstack
      become: true
      ansible.builtin.systemd_service:
        name: gpustack
        state: stopped
        enabled: true

- name: Stop GPUStack controller node
  hosts: controller
  tasks:
    - name: Stop GPUstack
      become: true
      ansible.builtin.systemd_service:
        name: gpustack
        state: stopped
        enabled: true
