---
- name: Output variables
  hosts: controllers
  tasks:
    - name: Get control panel URL & credentials
      ansible.builtin.debug:
        msg:
          - "URL:      http://{{ gpustack_server_host }}:{{ gpustack_server_port }}"
          - "Username: admin"
          - "Password: {{ gpustack_bootstrap_password }}"
