---
- name: Output variables
  hosts: controller
  tasks:
    - name: Get control panel URL & credentials
      ansible.builtin.debug:
        msg:
          - "URL:      http://{{ gpustack_server_host }}:{{ gpustack_server_port }}"
          - "Username: admin"
          - "Password: {{ gpustack_bootstrap_password }}"
    - name: Get grafana monitoring URL & credentials
      ansible.builtin.debug:
        msg:
          - "URL:      http://{{ grafana_server_host }}:{{ grafana_server_port }}"
          - "Username: {{ grafana_initial_admin_user }}"
          - "Password: {{ grafana_initial_admin_password }}"
